// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
)

const getOwnerByID = `-- name: GetOwnerByID :one
SELECT id, username, password_hash, display_name, created_at, updated_at
FROM owners
WHERE id = $1
`

func (q *Queries) GetOwnerByID(ctx context.Context, id string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByID, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnerByUsername = `-- name: GetOwnerByUsername :one
SELECT id, username, password_hash, display_name, created_at, updated_at
FROM owners
WHERE username = $1
`

func (q *Queries) GetOwnerByUsername(ctx context.Context, username string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByUsername, username)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
