// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (
    id,
    owner_id,
    type,
    title,
    image_url,
    source_url,
    review,
    consumed_on
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id,
          owner_id,
          type,
          title,
          image_url,
          source_url,
          review,
          consumed_on,
          created_at,
          updated_at
`

type CreateJournalEntryParams struct {
	ID         uuid.UUID   `json:"id"`
	OwnerID    string      `json:"owner_id"`
	Type       string      `json:"type"`
	Title      string      `json:"title"`
	ImageURL   pgtype.Text `json:"image_url"`
	SourceURL  pgtype.Text `json:"source_url"`
	Review     pgtype.Text `json:"review"`
	ConsumedOn pgtype.Date `json:"consumed_on"`
}

type CreateJournalEntryRow struct {
	ID         uuid.UUID          `json:"id"`
	OwnerID    string             `json:"owner_id"`
	Type       string             `json:"type"`
	Title      string             `json:"title"`
	ImageURL   pgtype.Text        `json:"image_url"`
	SourceURL  pgtype.Text        `json:"source_url"`
	Review     pgtype.Text        `json:"review"`
	ConsumedOn pgtype.Date        `json:"consumed_on"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (CreateJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.ID,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.ImageURL,
		arg.SourceURL,
		arg.Review,
		arg.ConsumedOn,
	)
	var i CreateJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.ImageURL,
		&i.SourceURL,
		&i.Review,
		&i.ConsumedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJournalEntryByIDAndOwner = `-- name: DeleteJournalEntryByIDAndOwner :execrows
DELETE FROM journal_entries
WHERE id = $1
  AND owner_id = $2
`

type DeleteJournalEntryByIDAndOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
}

func (q *Queries) DeleteJournalEntryByIDAndOwner(ctx context.Context, arg DeleteJournalEntryByIDAndOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJournalEntryByIDAndOwner, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJournalEntryByIDAndOwner = `-- name: GetJournalEntryByIDAndOwner :one
SELECT id,
       owner_id,
       type,
       title,
       image_url,
       source_url,
       review,
       consumed_on,
       created_at,
       updated_at
FROM journal_entries
WHERE id = $1
  AND owner_id = $2
`

type GetJournalEntryByIDAndOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
}

type GetJournalEntryByIDAndOwnerRow struct {
	ID         uuid.UUID          `json:"id"`
	OwnerID    string             `json:"owner_id"`
	Type       string             `json:"type"`
	Title      string             `json:"title"`
	ImageURL   pgtype.Text        `json:"image_url"`
	SourceURL  pgtype.Text        `json:"source_url"`
	Review     pgtype.Text        `json:"review"`
	ConsumedOn pgtype.Date        `json:"consumed_on"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetJournalEntryByIDAndOwner(ctx context.Context, arg GetJournalEntryByIDAndOwnerParams) (GetJournalEntryByIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByIDAndOwner, arg.ID, arg.OwnerID)
	var i GetJournalEntryByIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.ImageURL,
		&i.SourceURL,
		&i.Review,
		&i.ConsumedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJournalEntriesByOwner = `-- name: ListJournalEntriesByOwner :many
SELECT id,
       owner_id,
       type,
       title,
       image_url,
       source_url,
       review,
       consumed_on,
       created_at,
       updated_at
FROM journal_entries
WHERE owner_id = $1
ORDER BY consumed_on DESC, created_at DESC
`

type ListJournalEntriesByOwnerParams struct {
	OwnerID string `json:"owner_id"`
}

type ListJournalEntriesByOwnerRow struct {
	ID         uuid.UUID          `json:"id"`
	OwnerID    string             `json:"owner_id"`
	Type       string             `json:"type"`
	Title      string             `json:"title"`
	ImageURL   pgtype.Text        `json:"image_url"`
	SourceURL  pgtype.Text        `json:"source_url"`
	Review     pgtype.Text        `json:"review"`
	ConsumedOn pgtype.Date        `json:"consumed_on"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListJournalEntriesByOwner(ctx context.Context, arg ListJournalEntriesByOwnerParams) ([]ListJournalEntriesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByOwner, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalEntriesByOwnerRow
	for rows.Next() {
		var i ListJournalEntriesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Type,
			&i.Title,
			&i.ImageURL,
			&i.SourceURL,
			&i.Review,
			&i.ConsumedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJournalEntry = `-- name: UpdateJournalEntry :one
UPDATE journal_entries
SET type = $1,
    title = $2,
    image_url = $3,
    source_url = $4,
    review = $5,
    consumed_on = $6,
    updated_at = $7
WHERE id = $8
  AND owner_id = $9
RETURNING id,
          owner_id,
          type,
          title,
          image_url,
          source_url,
          review,
          consumed_on,
          created_at,
          updated_at
`

type UpdateJournalEntryParams struct {
	Type       string             `json:"type"`
	Title      string             `json:"title"`
	ImageURL   pgtype.Text        `json:"image_url"`
	SourceURL  pgtype.Text        `json:"source_url"`
	Review     pgtype.Text        `json:"review"`
	ConsumedOn pgtype.Date        `json:"consumed_on"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         uuid.UUID          `json:"id"`
	OwnerID    string             `json:"owner_id"`
}

type UpdateJournalEntryRow struct {
	ID         uuid.UUID          `json:"id"`
	OwnerID    string             `json:"owner_id"`
	Type       string             `json:"type"`
	Title      string             `json:"title"`
	ImageURL   pgtype.Text        `json:"image_url"`
	SourceURL  pgtype.Text        `json:"source_url"`
	Review     pgtype.Text        `json:"review"`
	ConsumedOn pgtype.Date        `json:"consumed_on"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) (UpdateJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, updateJournalEntry,
		arg.Type,
		arg.Title,
		arg.ImageURL,
		arg.SourceURL,
		arg.Review,
		arg.ConsumedOn,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i UpdateJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.ImageURL,
		&i.SourceURL,
		&i.Review,
		&i.ConsumedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
