// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Owner struct {
	ID           string             `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Todo struct {
	ID        uuid.UUID          `json:"id"`
	OwnerID   string             `json:"owner_id"`
	Title     string             `json:"title"`
	Completed bool               `json:"completed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
