// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, owner_id, title, completed)
VALUES ($1, $2, $3, false)
RETURNING id, owner_id, title, completed, created_at, updated_at
`

type CreateTodoParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
	Title   string    `json:"title"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.ID, arg.OwnerID, arg.Title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodoByIDAndOwner = `-- name: DeleteTodoByIDAndOwner :execrows
DELETE FROM todos
WHERE id = $1
  AND owner_id = $2
`

type DeleteTodoByIDAndOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
}

func (q *Queries) DeleteTodoByIDAndOwner(ctx context.Context, arg DeleteTodoByIDAndOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTodoByIDAndOwner, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTodoByIDAndOwner = `-- name: GetTodoByIDAndOwner :one
SELECT id, owner_id, title, completed, created_at, updated_at
FROM todos
WHERE id = $1
  AND owner_id = $2
`

type GetTodoByIDAndOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
}

func (q *Queries) GetTodoByIDAndOwner(ctx context.Context, arg GetTodoByIDAndOwnerParams) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByIDAndOwner, arg.ID, arg.OwnerID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodosByOwner = `-- name: ListTodosByOwner :many
SELECT id, owner_id, title, completed, created_at, updated_at
FROM todos
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTodosByOwner(ctx context.Context, ownerID string) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $3,
    completed = $4,
    updated_at = $5
WHERE id = $1
  AND owner_id = $2
RETURNING id, owner_id, title, completed, created_at, updated_at
`

type UpdateTodoParams struct {
	ID        uuid.UUID          `json:"id"`
	OwnerID   string             `json:"owner_id"`
	Title     string             `json:"title"`
	Completed bool               `json:"completed"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Completed,
		arg.UpdatedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
